version: '3.8'
services:
  postgres:
    container_name: my_postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ = Asia/Karachi
      - PGTZ = Asia/Karachi
    ports:
      - '5432:5432'
    volumes: 
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    container_name: my_pgadmin4
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  postgres-db:
    driver: local
  pgadmin-data:
    driver: local